### ISSUE TITLE
JsHint

### ISSUE THREAD

**Issue by ExtraGravity** [CalebJohn/potential-fortnight#10]
The code currently is not up to snuff according to JsHint, a future pull request will need to fix this.

**Comment by CalebJohn** [comment]
I was never really planning on keeping our code up to snuff with JsHint 100%. I was thinking to mostly use it for critical stuff, but if we do want to use it more strictly I would suggest setting it up as a step in Travis so that we can monitor all of our pulls.

**Comment by ExtraGravity** [comment]
I don't think JsHint plays too nicely with phaser, so I guess we'll just keep it as a check for ourselves. Not a full step in travis.

**Comment by CalebJohn** [comment]
I already have it added in Travis and it's not giving any errors, it looks like its just doing error checking as opposed to a full analysis. Check it out [here](https://travis-ci.org/CalebJohn/potential-fortnight/builds/107157552).

**Comment by ExtraGravity** [comment]
That works (y) this issue is resolved then?

**Comment by CalebJohn** [comment]
While the issue is up I'd like to discuss to what extent we want to use jshint, do you think that we should be using it to completely adhere to a particular style, or would error checking be enough? 

I think error checking is enough for us, but I am open to discussion around this.

**Comment by ExtraGravity** [comment]
I think error checking is enough.

**Comment by CalebJohn** [comment]
I'll close this issue then.
