### ISSUE TITLE
Proposal For Copywriting

### ISSUE THREAD

**Issue by ewuoso** [CalebJohn/potential-fortnight#103]
Hello i went through your project and i want to say it is very nice. However i noticed you are missing out some important details like gaq, about us and privacy policy which users will be looking forward too. If you dont mind i can write that for you

contact me
email ewuosoolusesi@gmail.com

steemit.com/@ewuoso

**Comment by clayjohn** [comment]
We are not looking for that right now as they are unnecessary for the project in its current state. If you would like to contribute on the code itself feel free.
