### ISSUE TITLE
WebGL Check

### ISSUE THREAD

**Issue by CalebJohn** [CalebJohn/potential-fortnight#15]
Because of our reliance on using WebGL to render significant parts of our game, I think that its best if we put in some code to alert the player if WebGL is not available and they will not be able to play.

**Comment by ExtraGravity** [comment]
I'll try to handle this

**Comment by ExtraGravity** [comment]
So this piece of code is sufficient to check if WebGL is enabled

``` javascript
var supportsWebGL = ( function () { try { return !! window.WebGLRenderingContext && !! document.createElement( 'canvas' ).getContext( 'experimental-webgl' ); } catch( e ) { return false; } } )();
```
