### ISSUE TITLE
Main GUI

### ISSUE THREAD

**Issue by CalebJohn** [CalebJohn/potential-fortnight#22]
We need to discuss how we want to arrange the buttons / messages in the primary GUI.
If we do want a more dynamic button type then we need to make sure our gui system supports dynamic placement of buttons.

**Comment by ExtraGravity** [comment]
In terms of GUI design, I think we should talk to our artist about that :)

**Comment by clayjohn** [comment]
We are going to want to add every visual item into a group in order to sort the draw order effectively. I cannot find a better way to control draw orders.

**Comment by clayjohn** [comment]
Currently in our main level function we destroy all of our buttons each time we enter a location and recreate them. What I think we should do is store a button group object with each sector that holds all the location dependent buttons and then have a separate object in the main level that holds the buttons that don't change (map, return, scene, etc.). This should not be hard to implement, it just means that we need to add a reference to the current sector in the level then change that reference when we click on a different tile. Currently all we do is display a different button type, I think by doing this we are opening up the sector data to be more accessible which should be important later on.

**Comment by clayjohn** [comment]
Irrelevant with new Godot build.
