### ISSUE TITLE
Sector object

### ISSUE THREAD

**Issue by CalebJohn** [CalebJohn/potential-fortnight#24]
This will be an object that stores information related to the local map view, in some ways it will be similar to the WorldData object, in that it contains geographic information (at a finer resolution).

This should also contain the base object (if any) that is in this sector.

**Comment by CalebJohn** [comment]
Types of Sectors:
- Rocky - Spelunk
- Fertile - Bushwack
- Humid - Dive
- Mountainous - Climb

Archetypes:
- Metals, -ionite,
- Stones, -stone, 
- Plants, -us, 
- Liquids, -orious,

**Comment by CalebJohn** [comment]
Suggestions for archetype properties?

**Comment by clayjohn** [comment]
- Hardness (or durability)
- Potential Energy
- Activation Energy (kind of like flammability)
- malleability/flexibility (how easy it is to build things with)

**Comment by ExtraGravity** [comment]
I feel like we can build malleability/flexibility into hardness, so when you build something out of a material: 
1. If it has high hardness, it will be difficult to make a building out of it, but it will last a long time.
2. If it has low hardness, it will be easy to make a building out of it, but it will break down quickly.

**Comment by ExtraGravity** [comment]
How about for the prototype we just have those 3

Hardness
Potential Energy
Activation Energy

**Comment by CalebJohn** [comment]
Sectors should maintain their own list of buttons, this should be in the form of a button group.

**Comment by ExtraGravity** [comment]
I think this is done?

**Comment by clayjohn** [comment]
We still need to add the material information.

**Comment by clayjohn** [comment]
Everything that was addressed in this issue is in now. SectorData will still need work in the future but a new issue will need to be created for that.
