### ISSUE TITLE
Scene generator

### ISSUE THREAD

**Issue by CalebJohn** [CalebJohn/potential-fortnight#27]
I don't there's much I can say here.

**Comment by clayjohn** [comment]
I've got this mainly set up, there is a few things I wanna change to make it more useful but then I will make a pull request.

**Comment by CalebJohn** [comment]
This should be it's own object, without it's own gamestate.
This should also be used as a form of prospecting for resources.

**Comment by ExtraGravity** [comment]
I think this is done?

**Comment by clayjohn** [comment]
Things to improve:

**Tech**
- [ ] speed (optimize for rendering a single frame)

**Style**
- [ ] depends on colors of map

- [ ] atmospheric/physical properties based on planet data

- [ ] Add dynamic day/night

- [ ] Other planets in sky

- [ ] Clouds

- [ ] Water

- [ ] Maybe plants/shrubbery
