### ISSUE TITLE
Button animation

### ISSUE THREAD

**Issue by CalebJohn** [CalebJohn/potential-fortnight#29]
Button should be more responsive and animated.

This should be looked at after #28 because it will depend on some of the changes there.

**Comment by ExtraGravity** [comment]
I think this is done?

**Comment by CalebJohn** [comment]
Not yet, I created this issue after the current button was already merged in master. What I want to see for this issue is some form of animation to show the passage of some time delay.

**Comment by clayjohn** [comment]
We can achieve this with a filter. Which either changes the color of (or fades out) the button.

**Comment by CalebJohn** [comment]
Superseded (is that the right word) by #65
