### ISSUE TITLE
Cutscene loading

### ISSUE THREAD

**Issue by clayjohn** [CalebJohn/potential-fortnight#34]
Not sure why this is. But when we make things in the world generator everything runs before the screen gets a chance to display. So after pressing 'start' we get a white screen while the generator runs, and then after you see that it has finished in the console, then the loading screen comes up and runs. 

We need to figure out what is wrong here and get the world generator running while the loading screen displays.

**Comment by clayjohn** [comment]
Okay I did some tests. When I put generateworld() at the end of beginCutscene then the screen would still stay white until it was done, but the cutscene would already be almost finished. 

So I think our issue is that Phaser doesn't display sprites until the end of create maybe? So I think we need to do something and get the cutscene started beforehand, or at least display the images it will be using beforehand. Because I have a feeling the cutscene is working fine its just not displaying the images until after the generator is finished.

**Comment by CalebJohn** [comment]
Okay, so I've been working on this issue for a couple of days now and I think I have a solid idea around how this can be resolved, unfortunately it means removing the cutscene state.  Hear me out.

Right now I think we have the the function of the cutscene state backwards, we are using it as a loading screen when it's function should be to play animations for the purpose of driving story/tutorials.

What I'm proposing is removing the cutscene state in favour of performing pregame loading using a sunset/rise animation in the menu state and following in the footsteps of A Dark Room (kinda) and making  a story clear without cutscenes and  using minimalist controls that don't require a tutorial. 

If we find that we need to perform state switching (beyond a menu-levelone transition) I think it should be handled in specialised start and entry functions that call into functions like generateWorld, that way we can animate the entrance and exits of the states seamlessly into one another.

I'll be following this with a pull request that removes the Cutscene and handles the state transitions within their respective classes.

**Comment by clayjohn** [comment]
I think thats a good plan especially for the prototype. I have the map generation set up and its pretty quick. So i dont think we dont need to worrry about having another whole scene. And realistically the whole cutscene setup doesnt really fit with our theme anyway. We really want to integrate everything into the level scene.
