### ISSUE TITLE
Perlin Uncaught Syntax Error

### ISSUE THREAD

**Issue by ExtraGravity** [CalebJohn/potential-fortnight#40]
When I run the page in chrome and press start. In the dev console it says

```
Uncaught SyntaxError: Unexpected token =
```

This happens on line 316 of `perlin.js`, jshint thinks it's fine and I can't see anything visibly wrong myself. Ideas?

**Comment by clayjohn** [comment]
This one Is a result of using default paramater syntax in the function fbm2. If we want to use ES6 standards then this should be fine. But it will need to be changed if we want to support ES5.
