### ISSUE TITLE
Remove Full screen from game

### ISSUE THREAD

**Issue by CalebJohn** [CalebJohn/potential-fortnight#43]
This is just causing bugs and should be removed to make room for new features.

**Comment by ExtraGravity** [comment]
What kind of bugs has it caused? If we are removing it, we should look into scaling everything for larger screen sizes.

**Comment by clayjohn** [comment]
The issue that arises is that when we resize we have to regenerate all of our assets again. Right now it is causing trouble with a PR I'm working on. But I can also see it causing issues when we are further along.

**Comment by CalebJohn** [comment]
To clarify the issue is dynamically resizing, correct? As long as the game stays with one resolution I think we're okay.

**Comment by clayjohn** [comment]
Also we discussed haveing an HTML element beside the canvas where we would output all of our messages to in order to avoid making our own text canvas within phaser.

**Comment by CalebJohn** [comment]
With the move to godot I think we're safe to **consider** a full screen option again.
