### ISSUE TITLE
Materials

### ISSUE THREAD

**Issue by CalebJohn** [CalebJohn/potential-fortnight#44]
First of all, most of what is to follow comes from Enoch's beautiful brain.

After some discussion with @enochtsang we're not going to go with a complex naming scheme, instead we should go with something "simple" and with tighter integration to material properties, which I'll outline below.

We should only refer to materials by their archetype (wood, stone, etc) the exact names are open for discussion. Along with this, materials will be unique to each planet so Earth wood does not have the same properties as Endor wood.

There will also be multiple grades of each material these will be the same materials on one planet that display different properties. The idea here is that it's the same material but a higher quality variant, think living vs dead wood or in more extreme cases, water vs oil.

Something more on the implementation side is the distinction between materials. My suggestion would be to have no distinction on the scale for the properties(hardness etc), but there would be caps, for example on a scale from 0-100, stone couldn't go below 20 but could reach to 100, metal might go 5-90 and any liquid would be stuck at 0.
I think this fits with a building system where we need to use a material that's hard enough or one with a high enough energy desire but we can ignore the name. From the player perspective though you could still relate stone to high hardness and wood to accessible energy.

What I would still like to discuss is how variability should work between grades (should stone with different grade only vary in hardness? Or should we also see variation in the other properties)

Of course all of this is up for debate, so please make corrections as needed.

As for how these materials are accessed i think that's a topic for another pull request.

**Comment by ExtraGravity** [comment]
I'll work on this tonight :)

**Comment by ExtraGravity** [comment]
I think there should be variation for all properties between grades. But at the same time, we should be very generous about how many small caps we give, like many objects will have many property limits between 0-5 and stuff like that.
