### ISSUE TITLE
Remove Hard coding of resources

### ISSUE THREAD

**Issue by CalebJohn** [CalebJohn/potential-fortnight#62]
This is especially referencing `getResources` and `getGatherers` of BaseObject.js.

The alternative should be storing resources names in one globally accessible location, we can also add some type of enum to make accessing this list more friendly.

e.g.
```javascript
var resourceNames = ["Wood", "Stone"];
var rsrcs = {Wood: 0, Stone:1};
```

**Comment by clayjohn** [comment]
Is this so we can loop over the elements of `resourceNames` instead of specifying them one-by-one in the function `getResources` and the like?

**Comment by clayjohn** [comment]
Okay so for the implementation I'm going to store anything indexed by resource types into arrays which follow the order set out in the global variable `resourceNames`
