### ISSUE TITLE
Menu buttons Signals

### ISSUE THREAD

**Issue by CalebJohn** [CalebJohn/potential-fortnight#77]
Why are the menu buttons connected through script instead of using signals in the editor? If it's a preference thing that's fine, I just want to make sure I follow the same way in the future.

**Comment by clayjohn** [comment]
It's because I only found out you could connect through the editor a few minutes before I made the PR. I found out by accident. We can switch them all over without any problems.

**Comment by clayjohn** [comment]
this was addressed in #78
